import { useEffect, useState } from 'react'
import { Check, Clipboard, Download, ExternalLink, LogOut, RefreshCw, Send } from 'lucide-react'
import { downloadJson } from '../utils/download'

const token = () => sessionStorage.getItem('swimtimer-admin-token')
const authFetch = (url, options = {}) => fetch(url, { ...options, headers: { ...options.headers, Authorization: `Bearer ${token()}` } })

export default function AdminDashboard() {
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  const [generating, setGenerating] = useState(false)
  const [detail, setDetail] = useState(null)
  const [copied, setCopied] = useState('')
  const load = async () => { try { const response = await authFetch('/api/admin/dashboard'); if (response.status === 401) return logout(); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result); setError('') } catch (err) { setError(err.message) } }
  useEffect(() => { load() }, [])
  const logout = () => { sessionStorage.removeItem('swimtimer-admin-token'); window.location.reload() }
  const generate = async () => { setGenerating(true); try { const response = await authFetch('/api/admin/generate-tokens', { method: 'POST' }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await load() } catch (err) { setError(err.message) } finally { setGenerating(false) } }
  const registrationUrl = id => `${window.location.origin}/inscribir?t=${encodeURIComponent(id)}`
  const copy = async id => { await navigator.clipboard.writeText(registrationUrl(id)); setCopied(id); setTimeout(() => setCopied(''), 1500) }
  const viewDetail = async club => { try { const response = await authFetch(`/api/admin/inscription/${club.code}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); setDetail(result) } catch (err) { setError(err.message) } }
  const exportAll = async () => { const response = await authFetch('/api/admin/export-all'); const result = await response.json(); if (response.ok) downloadJson(result, 'swimtimer-consolidado.json'); else setError(result.error) }
  if (!data) return <div className="flex min-h-screen items-center justify-center">{error || 'Cargando panel…'}</div>
  return <><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-4"><img src="/logo.svg" className="size-10" alt="" /><div className="mr-auto"><h1 className="font-bold text-brand-800">SWIMTIMER · Organizador</h1><p className="text-xs text-slate-500">Panel administrativo</p></div><button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={logout}><LogOut className="size-4" />Salir</button></div></header>
  <main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><section className="card p-5"><p className="text-sm font-semibold text-brand-600">Evento activo</p><h2 className="mt-1 text-xl font-bold">{data.event.name}</h2><p className="mt-1 text-sm text-slate-500">{data.event.date} · {data.event.venue}</p></section>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Clubes',data.counts.total_clubs],['Recibidas',data.counts.received],['Pendientes',data.counts.pending],['Nadadores',data.counts.athletes]].map(([label,value]) => <div className="card p-4" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-brand-800">{value}</p></div>)}</section>
    {error && <p className="rounded-lg bg-danger-50 p-3 text-danger-700">{error}</p>}
    <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-bold">Clubes y enlaces</h2><p className="text-sm text-slate-500">Seguimiento de invitaciones e inscripciones</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={exportAll}><Download className="size-4" />Consolidado</button><button className="btn-primary inline-flex items-center gap-2 text-sm" onClick={generate} disabled={generating}><RefreshCw className={`size-4 ${generating ? 'animate-spin' : ''}`} />Generar enlaces</button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Estado</th><th className="p-3">Club</th><th className="p-3">Nadadores</th><th className="p-3">Envío</th><th className="p-3">Acciones</th></tr></thead><tbody>{data.clubs.map(club => <tr key={club.code} className="border-t"><td className="p-3"><Status status={club.status} /></td><td className="p-3 font-semibold">{club.name}</td><td className="p-3">{club.athlete_count || '—'}</td><td className="p-3 text-slate-500">{club.submitted_at ? new Date(club.submitted_at).toLocaleString('es-VE') : '—'}</td><td className="p-3"><div className="flex items-center gap-1">{club.token && <><button title="Copiar enlace" className="rounded p-2 hover:bg-slate-100" onClick={() => copy(club.token)}>{copied === club.token ? <Check className="size-4 text-success-800" /> : <Clipboard className="size-4" />}</button><a title="Abrir enlace" className="rounded p-2 hover:bg-slate-100" href={registrationUrl(club.token)} target="_blank" rel="noreferrer"><ExternalLink className="size-4" /></a><a title="Compartir por WhatsApp" className="rounded p-2 hover:bg-slate-100" href={`https://wa.me/?text=${encodeURIComponent(`Invitación para inscribir a ${club.name}: ${registrationUrl(club.token)}`)}`} target="_blank" rel="noreferrer"><Send className="size-4" /></a></>}{club.status === 'received' && <button className="ml-2 font-semibold text-brand-600" onClick={() => viewDetail(club)}>Ver detalle</button>}</div></td></tr>)}</tbody></table></div>
    </section></main>{detail && <Detail inscription={detail} onClose={() => setDetail(null)} />}</>
}

function Status({ status }) { const map = { received: ['bg-success-50 text-success-800','● Recibida'], sent: ['bg-amber-50 text-amber-800','● Enlace enviado'], missing: ['bg-danger-50 text-danger-700','● Sin enlace'] }; return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${map[status][0]}`}>{map[status][1]}</span> }
function Detail({ inscription, onClose }) { return <div className="fixed inset-0 z-20 overflow-y-auto bg-slate-950/40 p-4"><section className="card mx-auto max-w-4xl p-5 sm:p-6"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">{inscription.meta.club_name}</h2><p className="text-sm text-slate-500">{inscription.athletes.length} nadadores · {inscription.results.length} inscripciones</p></div><button className="btn-secondary" onClick={onClose}>Cerrar</button></div><div className="mt-5 space-y-3">{inscription.roster?.map(athlete => <div key={athlete.id} className="rounded-lg border p-3"><p className="font-bold">{athlete.lastName}, {athlete.firstName} · {athlete.sex} · {athlete.age} años</p><p className="mt-1 text-sm text-slate-600">{athlete.events.map(item => `${item.label}: ${item.time}`).join(' · ')}</p></div>)}</div><button className="btn-primary mt-5 inline-flex items-center gap-2" onClick={() => downloadJson(inscription, `inscripcion-${inscription.meta.club_code}.json`)}><Download className="size-4" />Descargar JSON</button></section></div> }
