import { useEffect, useState } from 'react'
import { Archive, Check, Clipboard, Download, ExternalLink, Pencil, RefreshCw, Send } from 'lucide-react'
import { downloadJson } from '../utils/download'
import { exportAll as exportAllData, generateTokens, getDashboard, getInscription, updateEventStatus } from '../services/api'
import AdminHeader from '../components/AdminHeader'

export default function AdminDashboard({ eventId }) {
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  const [generating, setGenerating] = useState(false)
  const [detail, setDetail] = useState(null)
  const [copied, setCopied] = useState('')
  const load = async () => { try { setData(await getDashboard(eventId)); setError('') } catch (error) { setError(error.message) } }
  useEffect(() => { load() }, [eventId])
  const generate = async () => { setGenerating(true); try { await generateTokens(eventId); await load() } catch (error) { setError(error.message) } finally { setGenerating(false) } }
  const registrationUrl = id => `${window.location.origin}/inscribir?t=${encodeURIComponent(id)}`
  const copy = async id => { await navigator.clipboard.writeText(registrationUrl(id)); setCopied(id); setTimeout(() => setCopied(''), 1500) }
  const viewDetail = async club => { try { setDetail(await getInscription(eventId, club.code)) } catch (error) { setError(error.message) } }
  const exportAll = async () => { try { downloadJson(await exportAllData(eventId), `swimtimer-${eventId}.json`) } catch (error) { setError(error.message) } }
  const archive = async () => { if (window.confirm('¿Archivar este evento? Podrás seguir consultando sus datos.')) { await updateEventStatus(eventId, 'archived'); await load() } }
  if (!data) return <div className="flex min-h-screen items-center justify-center">{error || 'Cargando panel…'}</div>
  return <><AdminHeader><a href="/admin/eventos" className="btn-secondary hidden text-sm sm:inline-flex">← Mis eventos</a></AdminHeader><main className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><a href="/admin/eventos" className="text-sm font-bold text-brand-800">← Volver a mis eventos</a><div className="mt-3 flex flex-wrap items-center gap-3"><StatusBadge status={data.event.status} /><h1 className="text-2xl font-extrabold">{data.event.name}</h1></div><p className="mt-2 text-sm text-slate-500">{data.event.date_start} · {data.event.venue}</p></div><div className="flex flex-wrap gap-2"><a className="btn-secondary inline-flex items-center gap-2 text-sm" href={`/admin/eventos/${eventId}/editar`}><Pencil className="size-4" />Editar evento</a>{!['archived'].includes(data.event.status) && <button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={archive}><Archive className="size-4" />Archivar</button>}</div></div>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Clubes',data.counts.total_clubs],['Recibidas',data.counts.received],['Pendientes',data.counts.pending],['Nadadores',data.counts.athletes]].map(([label,value]) => <div className="card p-4" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-extrabold text-brand-800">{value}</p></div>)}</section>
    {error && <p className="rounded-lg bg-danger-50 p-3 text-danger-700">{error}</p>}
    <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-bold">Clubes y enlaces</h2><p className="text-sm text-slate-500">Seguimiento de invitaciones e inscripciones</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={exportAll}><Download className="size-4" />Consolidado</button><button className="btn-primary inline-flex items-center gap-2 text-sm" onClick={generate} disabled={generating}><RefreshCw className={`size-4 ${generating ? 'animate-spin' : ''}`} />Generar enlaces</button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Estado</th><th className="p-3">Club</th><th className="p-3">Nadadores</th><th className="p-3">Envío</th><th className="p-3">Acciones</th></tr></thead><tbody>{data.clubs.map(club => <tr key={club.code} className="border-t transition hover:bg-slate-100"><td className="p-3"><ClubStatus status={club.status} /></td><td className="p-3 font-semibold">{club.name}</td><td className="p-3">{club.athlete_count || '—'}</td><td className="p-3 text-slate-500">{club.submitted_at ? new Date(club.submitted_at).toLocaleString('es-VE') : '—'}</td><td className="p-3"><div className="flex items-center gap-1">{club.token && <><button title="Copiar enlace" className="rounded p-2 hover:bg-slate-100" onClick={() => copy(club.token)}>{copied === club.token ? <Check className="size-4 text-success-800" /> : <Clipboard className="size-4" />}</button><a title="Abrir enlace" className="rounded p-2 hover:bg-slate-100" href={registrationUrl(club.token)} target="_blank" rel="noreferrer"><ExternalLink className="size-4" /></a><a title="Compartir por WhatsApp" className="rounded p-2 hover:bg-slate-100" href={`https://wa.me/?text=${encodeURIComponent(`Invitación para inscribir a ${club.name}: ${registrationUrl(club.token)}`)}`} target="_blank" rel="noreferrer"><Send className="size-4" /></a></>}{club.status === 'received' && <button className="ml-2 font-semibold text-brand-800" onClick={() => viewDetail(club)}>Ver detalle</button>}</div></td></tr>)}</tbody></table></div>
    </section></main>{detail && <Detail inscription={detail} onClose={() => setDetail(null)} />}</>
}

function StatusBadge({ status }) { const labels = { active: 'Activo', draft: 'Borrador', closed: 'Cerrado', archived: 'Archivado' }; return <span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold uppercase tracking-wider text-brand-800">{labels[status] || status}</span> }
function ClubStatus({ status }) { const map = { received: ['bg-success-50 text-success-800','● Recibida'], sent: ['bg-warning-50 text-warning-800','● Enlace enviado'], missing: ['bg-danger-50 text-danger-700','● Sin enlace'] }; return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${map[status][0]}`}>{map[status][1]}</span> }
function Detail({ inscription, onClose }) { return <div className="fixed inset-0 z-20 overflow-y-auto bg-slate-950/70 p-4"><section className="card mx-auto max-w-4xl p-5 sm:p-6"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">{inscription.meta.club_name}</h2><p className="text-sm text-slate-500">{inscription.athletes.length} nadadores · {inscription.results.length} inscripciones</p></div><button className="btn-secondary" onClick={onClose}>Cerrar</button></div><div className="mt-5 space-y-3">{inscription.roster?.map(athlete => <div key={athlete.id} className="rounded-lg border bg-slate-100 p-3"><p className="font-bold">{athlete.lastName}, {athlete.firstName} · {athlete.sex} · {athlete.age} años</p><p className="mt-1 text-sm text-slate-600">{athlete.events.map(item => `${item.label}: ${item.time}`).join(' · ')}</p></div>)}</div><button className="btn-primary mt-5 inline-flex items-center gap-2" onClick={() => downloadJson(inscription, `inscripcion-${inscription.meta.club_code}.json`)}><Download className="size-4" />Descargar JSON</button></section></div> }
