import { useEffect, useState } from 'react'
import { Archive, Clipboard, ExternalLink, Mail, MessageCircle, Pencil, RefreshCw, Send, Trash2 } from 'lucide-react'
import AdminHeader from '../components/AdminHeader'
import CloseRegistrationModal from '../components/CloseRegistrationModal'
import ExportMenu from '../components/ExportMenu'
import LateReviewPanel from '../components/LateReviewPanel'
import LinkDistributionModal from '../components/LinkDistributionModal'
import DeleteEventModal from '../components/DeleteEventModal'
import { downloadJson } from '../utils/download'
import { emailInvitation, whatsappInvitation } from '../utils/messageTemplates'
import { deleteEvent, exportAll, generateTokens, getDashboard, getInscription, reviewLate, setClubParticipation, updateEventStatus } from '../services/api'

export default function AdminDashboard({ eventId }) {
  const [data, setData] = useState(null)
  const [error, setError] = useState('')
  const [generating, setGenerating] = useState(false)
  const [detail, setDetail] = useState(null)
  const [distributionOpen, setDistributionOpen] = useState(false)
  const [closeOpen, setCloseOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [toast, setToast] = useState('')
  const load = async () => { try { const result = await getDashboard(eventId); setData(result); setError(''); return result } catch (error) { setError(error.message) } }
  useEffect(() => { load() }, [eventId])
  const generate = async () => { setGenerating(true); try { await generateTokens(eventId); await load() } catch (error) { setError(error.message) } finally { setGenerating(false) } }
  const registrationUrl = id => `${window.location.origin}/inscribir?t=${encodeURIComponent(id)}`
  const copyText = async (text, message = 'Enlace copiado') => { await navigator.clipboard.writeText(text); setToast(message); setTimeout(() => setToast(''), 1800) }
  const viewDetail = async club => { try { setDetail(await getInscription(eventId, club.code)) } catch (error) { setError(error.message) } }
  const download = async type => { try { const output = await exportAll(eventId, type); downloadJson(output, `swimtimer-${eventId}-${type}.json`) } catch (error) { setError(error.message) } }
  const changeStatus = async status => { await updateEventStatus(eventId, status); setCloseOpen(false); await load() }
  const archive = async () => { if (window.confirm('¿Archivar este evento? Podrás seguir consultando sus datos.')) await changeStatus('archived') }
  const openDistribution = async () => { if (data.clubs.some(club => !club.token)) { await generateTokens(eventId); await load() } setDistributionOpen(true) }
  const handleReview = async (clubCode, action, ids) => { await reviewLate(eventId, clubCode, action, ids); await load() }
  const toggleParticipation = async club => { await setClubParticipation(eventId, club.code, club.status === 'not_participating'); await load() }
  const requestDelete = () => {
    if (['active', 'accepting_late'].includes(data.event.status)) { setError('Cierra las inscripciones antes de eliminar el evento.'); return }
    setDeleteOpen(true)
  }
  const confirmDelete = async () => { await deleteEvent(eventId); window.location.href = '/admin/eventos' }
  if (!data) return <div className="flex min-h-screen items-center justify-center">{error || 'Cargando panel…'}</div>
  const pending = data.clubs.filter(club => !['received', 'not_participating'].includes(club.status))
  return <><AdminHeader><a href="/admin/eventos" className="btn-secondary hidden text-sm sm:inline-flex">← Mis eventos</a></AdminHeader><main className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6">
    {toast && <div className="fixed right-4 top-20 z-50 rounded-lg bg-success-50 px-4 py-3 font-bold text-success-800">{toast}</div>}
    <div className="flex flex-wrap items-start justify-between gap-3"><div><a href="/admin/eventos" className="text-sm font-bold text-brand-800">← Volver a mis eventos</a><div className="mt-3 flex flex-wrap items-center gap-3"><StatusBadge status={data.event.status} /><h1 className="text-2xl font-extrabold">{data.event.name}</h1></div><p className="mt-2 text-sm text-slate-500">{data.event.date_start} · {data.event.venue || 'Sede por definir'}</p></div><div className="flex flex-wrap gap-2"><a className="btn-secondary inline-flex items-center gap-2 text-sm" href={`/admin/eventos/${eventId}/editar`}><Pencil className="size-4" />Editar evento</a>{data.event.status === 'active' && <button className="btn-secondary text-sm" onClick={() => setCloseOpen(true)}>Cerrar inscripciones</button>}{data.event.status === 'accepting_late' && <button className="btn-secondary text-sm" onClick={() => setCloseOpen(true)}>Cerrar definitivamente</button>}{data.event.status === 'closed' && <button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={archive}><Archive className="size-4" />Archivar</button>}</div></div>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Clubes',data.counts.total_clubs],['Recibidas',data.counts.received],['Pendientes',data.counts.pending],['Nadadores',data.counts.athletes]].map(([label,value]) => <div className="card p-4" key={label}><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-3xl font-extrabold text-brand-800">{value}</p></div>)}</section>
    <section className="card grid gap-3 p-4 text-sm sm:grid-cols-3"><Timestamp label="Inscripciones abiertas desde" value={data.timestamps.opened_at} /><Timestamp label="Última inscripción recibida" value={data.timestamps.last_submission_at} /><Timestamp label="Inscripciones cerradas" value={data.timestamps.closed_at} /></section>
    {error && <p className="rounded-lg bg-danger-50 p-3 text-danger-700">{error}</p>}
    <LateReviewPanel submissions={data.late || []} onReview={handleReview} />
    <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-bold">Clubes y enlaces</h2><p className="text-sm text-slate-500">{pending.length ? `${pending.length} clubes todavía no han enviado` : 'Todos los clubes respondieron'}</p></div><div className="flex flex-wrap gap-2"><ExportMenu onExport={download} /><button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={load}><RefreshCw className="size-4" />Actualizar</button><button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={openDistribution}><Send className="size-4" />Distribuir enlaces a todos</button><button className="btn-primary inline-flex items-center gap-2 text-sm" onClick={generate} disabled={generating}><RefreshCw className={`size-4 ${generating ? 'animate-spin' : ''}`} />Generar enlaces</button></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1080px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Estado</th><th className="p-3">Club</th><th className="p-3">Nadadores</th><th className="p-3">Envío</th><th className="p-3">Acciones</th></tr></thead><tbody>{data.clubs.map(club => <tr key={club.code} className={`border-t transition hover:bg-slate-100 ${club.status === 'not_participating' ? 'bg-slate-100 text-slate-500' : ''}`}><td className="p-3"><ClubStatus status={club.status} /></td><td className="p-3 font-semibold">{club.name}<span className="ml-2 font-mono text-xs text-slate-500">{club.abbreviation}</span></td><td className="p-3">{club.athlete_count || '—'}</td><td className="p-3 text-slate-500">{club.submitted_at ? new Date(club.submitted_at).toLocaleString('es-VE') : '—'}</td><td className="p-3"><div className="flex flex-wrap items-center gap-1">{club.status === 'not_participating' ? <button className="btn-secondary px-2 py-1.5 text-xs" onClick={() => toggleParticipation(club)}>Reincorporar</button> : <button className="btn-secondary px-2 py-1.5 text-xs" onClick={() => toggleParticipation(club)}>Marcar como no participa</button>}{club.status !== 'not_participating' && club.token && <><button className="btn-secondary inline-flex items-center gap-1 px-2 py-1.5 text-xs" onClick={() => copyText(registrationUrl(club.token))}><Clipboard className="size-3" />Copiar</button><a className="btn-secondary inline-flex items-center gap-1 px-2 py-1.5 text-xs" href={registrationUrl(club.token)} target="_blank" rel="noreferrer"><ExternalLink className="size-3" />Abrir</a><a className="btn-secondary inline-flex items-center gap-1 px-2 py-1.5 text-xs" href={whatsappHref(data.event, club, registrationUrl(club.token))} target="_blank" rel="noreferrer"><MessageCircle className="size-3" />WhatsApp</a><a className="btn-secondary inline-flex items-center gap-1 px-2 py-1.5 text-xs" href={mailHref(data.event, registrationUrl(club.token))}><Mail className="size-3" />Correo</a></>}{club.status === 'received' && <button className="ml-2 font-semibold text-brand-800" onClick={() => viewDetail(club)}>Ver detalle</button>}</div></td></tr>)}</tbody></table></div>
    </section>
    <section className="mt-12 flex justify-end border-t border-danger-700/20 pt-6"><button className="inline-flex items-center gap-2 rounded-lg border border-danger-700 px-4 py-2.5 font-bold text-danger-700 transition hover:bg-danger-50" onClick={requestDelete}><Trash2 className="size-4" />Eliminar evento</button></section>
  </main>{detail && <Detail inscription={detail} onClose={() => setDetail(null)} />}{distributionOpen && <LinkDistributionModal event={data.event} clubs={data.clubs.filter(club => club.status !== 'not_participating')} urlFor={registrationUrl} onCopy={copyText} onClose={() => setDistributionOpen(false)} />}{closeOpen && <CloseRegistrationModal event={data.event} clubs={data.clubs} urlFor={registrationUrl} onSelect={changeStatus} onClose={() => setCloseOpen(false)} />}{deleteOpen && <DeleteEventModal event={data.event} onClose={() => setDeleteOpen(false)} onConfirm={confirmDelete} />}</>
}

function whatsappHref(event, club, url) { return `https://wa.me/${club.contact_whatsapp || ''}?text=${encodeURIComponent(whatsappInvitation(event, url))}` }
function mailHref(event, url) { const mail = emailInvitation(event, url); return `mailto:?subject=${encodeURIComponent(mail.subject)}&body=${encodeURIComponent(mail.body)}` }
function Timestamp({ label, value }) { return <div><p className="text-slate-500">{label}</p><p className="mt-1 font-bold">{value ? new Date(value).toLocaleString('es-VE') : '—'}</p></div> }
function StatusBadge({ status }) { const labels = { active: 'Inscripciones abiertas', accepting_late: 'Aceptando tardías', draft: 'Borrador', closed: 'Cerrado', archived: 'Archivado' }; return <span className={`rounded-full px-3 py-1 text-xs font-bold uppercase tracking-wider ${status === 'active' ? 'bg-success-800 text-white' : status === 'accepting_late' ? 'bg-warning-800 text-white' : 'bg-slate-200 text-slate-700'}`}>{labels[status] || status}</span> }
function ClubStatus({ status }) { const map = { received: ['bg-success-800 text-white','● Recibida'], sent: ['bg-warning-50 text-warning-800','● Enlace enviado'], missing: ['bg-danger-50 text-danger-700','● Sin enlace'], not_participating: ['bg-slate-200 text-slate-700','● No participa'] }; return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${map[status][0]}`}>{map[status][1]}</span> }
function Detail({ inscription, onClose }) { return <div className="fixed inset-0 z-20 overflow-y-auto bg-slate-950/70 p-4"><section className="card mx-auto max-w-4xl p-5 sm:p-6"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">{inscription.meta.club_name}</h2><p className="text-sm text-slate-500">{inscription.athletes.length} nadadores · {inscription.results.length} inscripciones</p></div><button className="btn-secondary" onClick={onClose}>Cerrar</button></div><div className="mt-5 space-y-3">{inscription.roster?.map(athlete => <div key={athlete.id} className="rounded-lg border bg-slate-100 p-3"><p className="font-bold">{athlete.lastName}, {athlete.firstName} · {athlete.sex} · {athlete.age} años</p><p className="mt-1 text-sm text-slate-600">{athlete.events.map(item => `${item.label}: ${item.time}`).join(' · ')}</p></div>)}</div><button className="btn-primary mt-5" onClick={() => downloadJson(inscription, `inscripcion-${inscription.meta.club_code}.json`)}>Descargar JSON del club</button></section></div> }
