import { Mail, MessageCircle, X } from 'lucide-react'
import { useState } from 'react'
import { emailInvitation, whatsappInvitation } from '../utils/messageTemplates'

export default function CloseRegistrationModal({ event, clubs, urlFor, onSelect, onClose }) {
  const pending = clubs.filter(club => !['received', 'not_participating'].includes(club.status))
  const participating = clubs.filter(club => club.status !== 'not_participating')
  const [showReminders, setShowReminders] = useState(false)
  return <div className="fixed inset-0 z-30 overflow-y-auto bg-slate-950/80 p-4"><section className="card mx-auto max-w-2xl p-5 sm:p-6"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-bold">Cerrar inscripciones</h2><p className="mt-1 text-slate-500">{participating.length - pending.length} de {participating.length} clubes participantes han enviado.</p></div><button className="rounded p-2 hover:bg-slate-100" onClick={onClose} aria-label="Cerrar"><X /></button></div>{pending.length > 0 && <div className="mt-5 rounded-xl bg-danger-50 p-4"><p className="font-bold text-danger-700">Clubes pendientes ({pending.length})</p><div className="mt-3 space-y-2">{pending.map(club => <div key={club.code} className="flex flex-wrap items-center gap-2"><span className="mr-auto text-danger-700">{club.name}</span>{showReminders && club.token && club.contact_whatsapp && <a className="rounded border px-2 py-1 text-xs text-danger-700" href={`https://wa.me/${club.contact_whatsapp}?text=${encodeURIComponent(`Recordatorio: ${whatsappInvitation(event, urlFor(club.token))}`)}`} target="_blank" rel="noreferrer"><MessageCircle className="mr-1 inline size-3" />WhatsApp</a>}{showReminders && club.token && <a className="rounded border px-2 py-1 text-xs text-danger-700" href={mailHref(event, urlFor(club.token))}><Mail className="mr-1 inline size-3" />Correo</a>}</div>)}</div><label className="mt-4 flex cursor-pointer items-center gap-2 border-t pt-3 text-sm text-danger-700"><input type="checkbox" checked={showReminders} onChange={event => setShowReminders(event.target.checked)} />¿Enviar recordatorio a clubes pendientes?</label></div>}<p className="mt-5 text-sm text-slate-500">Puedes permitir envíos tardíos sujetos a aprobación o cerrar definitivamente.</p><div className="mt-5 flex flex-wrap justify-end gap-2"><button className="btn-secondary" onClick={() => onSelect('closed')}>Cerrar definitivamente</button><button className="btn-primary" onClick={() => onSelect('accepting_late')}>Cerrar y aceptar tardías</button></div></section></div>
}
function mailHref(event, url) { const mail = emailInvitation(event, url); return `mailto:?subject=${encodeURIComponent(`Recordatorio: ${mail.subject}`)}&body=${encodeURIComponent(mail.body)}` }
