import { Mail, RefreshCw } from 'lucide-react'
import { useState } from 'react'

export default function EmailInvitationsPanel({ clubs, sending, results, onSendAll }) {
  const [showStatus, setShowStatus] = useState(false)
  const participating = clubs.filter(club => club.status !== 'not_participating')
  const withEmail = participating.filter(club => club.email)
  const missing = participating.filter(club => !club.email)
  return <section className="card p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold text-brand-800"><Mail className="size-5" />Invitaciones por correo</h2><p className="mt-1 text-sm text-slate-600">{withEmail.length} de {participating.length} clubes tienen correo configurado</p>{missing.length > 0 && <p className="mt-1 text-sm text-warning-800">{missing.length} sin correo: {missing.map(club => club.name).join(', ')}</p>}</div><div className="flex flex-wrap gap-2"><button className="btn-primary inline-flex items-center gap-2 text-sm" disabled={sending || !withEmail.length} onClick={onSendAll}>{sending ? <RefreshCw className="size-4 animate-spin" /> : <Mail className="size-4" />}Enviar invitaciones a todos</button><button className="btn-secondary text-sm" onClick={() => setShowStatus(!showStatus)}>Ver estado de envíos</button></div></div>{(showStatus || results.length > 0) && <div className="mt-4 space-y-2 border-t pt-4">{results.map((result, index) => <p key={`${result.clubCode || result.club}-${index}`} className={`rounded-lg p-2 text-sm ${result.success ? 'bg-success-50 text-success-800' : result.warning ? 'bg-warning-50 text-warning-800' : 'bg-danger-50 text-danger-700'}`}>{result.success ? '✅' : result.warning ? '⚠️' : '❌'} {result.club} {result.email ? `→ ${result.email}` : ''}{result.error ? ` (${result.error})` : ''}</p>)}{clubs.filter(club => club.invitation_sent_at || club.invitation_error).map(club => <p key={`status-${club.code}`} className={`text-sm ${club.invitation_error ? 'text-danger-700' : 'text-success-800'}`}>📧 {club.name}: {club.invitation_error ? `Error — ${club.invitation_error}` : `Invitación enviada ${new Date(club.invitation_sent_at).toLocaleString('es-VE')}`}</p>)}</div>}</section>
}
