import { Clipboard, Mail, MessageCircle, X } from 'lucide-react'
import { allLinksText, emailInvitation, whatsappInvitation } from '../utils/messageTemplates'

export default function LinkDistributionModal({ event, clubs, urlFor, onCopy, onClose }) {
  const copyAll = () => onCopy(allLinksText(event, clubs, urlFor), 'Todos los enlaces copiados')
  return <div className="fixed inset-0 z-30 overflow-y-auto bg-slate-950/80 p-4"><section className="card mx-auto max-w-3xl p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Distribuir enlaces a todos</h2><p className="mt-1 text-sm text-slate-500">{event.name}</p></div><button className="rounded p-2 hover:bg-slate-100" onClick={onClose} aria-label="Cerrar"><X /></button></div><button className="btn-primary mt-5 inline-flex items-center gap-2" onClick={copyAll}><Clipboard className="size-4" />Copiar todos los enlaces</button><div className="mt-5 divide-y rounded-xl border">{clubs.map(club => <div key={club.code} className="flex flex-wrap items-center gap-2 p-3"><div className="min-w-48 flex-1"><p className="font-bold">{club.name}</p><p className="font-mono text-xs text-slate-500">{club.token || 'Sin enlace'}</p></div>{club.token ? <><button className="btn-secondary inline-flex items-center gap-2 text-sm" onClick={() => onCopy(urlFor(club.token), 'Enlace copiado')}><Clipboard className="size-4" />Copiar</button>{club.contact_whatsapp && <a className="btn-secondary inline-flex items-center gap-2 text-sm" href={`https://wa.me/${club.contact_whatsapp}?text=${encodeURIComponent(whatsappInvitation(event, urlFor(club.token)))}`} target="_blank" rel="noreferrer"><MessageCircle className="size-4" />WhatsApp</a>}<a className="btn-secondary inline-flex items-center gap-2 text-sm" href={mailHref(event, urlFor(club.token))}><Mail className="size-4" />Correo</a></> : <span className="text-sm text-warning-800">Genera los enlaces primero</span>}</div>)}</div></section></div>
}

function mailHref(event, url) { const mail = emailInvitation(event, url); return `mailto:?subject=${encodeURIComponent(mail.subject)}&body=${encodeURIComponent(mail.body)}` }
